/** Display names keyed by logo filename stem under `public/leagues/{league}/`. */

export const NBA_TEAM_META: Record<string, { name: string; shortName: string }> = {
  hawks: { name: "Atlanta Hawks", shortName: "Hawks" },
  atlanta: { name: "Atlanta Hawks", shortName: "Hawks" },
  "boston-celtics": { name: "Boston Celtics", shortName: "Celtics" },
  celtics: { name: "Boston Celtics", shortName: "Celtics" },
  "brooklyn-nets": { name: "Brooklyn Nets", shortName: "Nets" },
  nets: { name: "Brooklyn Nets", shortName: "Nets" },
  "charlotte-hornets": { name: "Charlotte Hornets", shortName: "Hornets" },
  hornets: { name: "Charlotte Hornets", shortName: "Hornets" },
  "chicago bulls": { name: "Chicago Bulls", shortName: "Bulls" },
  bulls: { name: "Chicago Bulls", shortName: "Bulls" },
  "cleveland cavalie": { name: "Cleveland Cavaliers", shortName: "Cavaliers" },
  cavaliers: { name: "Cleveland Cavaliers", shortName: "Cavaliers" },
  "dallas mavericks": { name: "Dallas Mavericks", shortName: "Mavericks" },
  mavericks: { name: "Dallas Mavericks", shortName: "Mavericks" },
  "denver nuggets": { name: "Denver Nuggets", shortName: "Nuggets" },
  nuggets: { name: "Denver Nuggets", shortName: "Nuggets" },
  "detroit pistons": { name: "Detroit Pistons", shortName: "Pistons" },
  pistons: { name: "Detroit Pistons", shortName: "Pistons" },
  "golden state warr": { name: "Golden State Warriors", shortName: "Warriors" },
  warriors: { name: "Golden State Warriors", shortName: "Warriors" },
  "houston rockets": { name: "Houston Rockets", shortName: "Rockets" },
  rockets: { name: "Houston Rockets", shortName: "Rockets" },
  "indiana pacers": { name: "Indiana Pacers", shortName: "Pacers" },
  pacers: { name: "Indiana Pacers", shortName: "Pacers" },
  "los angeles clipp": { name: "LA Clippers", shortName: "Clippers" },
  clippers: { name: "LA Clippers", shortName: "Clippers" },
  "los angeles laker": { name: "Los Angeles Lakers", shortName: "Lakers" },
  lakers: { name: "Los Angeles Lakers", shortName: "Lakers" },
  "memphis grizzlies": { name: "Memphis Grizzlies", shortName: "Grizzlies" },
  grizzlies: { name: "Memphis Grizzlies", shortName: "Grizzlies" },
  "miami heat": { name: "Miami Heat", shortName: "Heat" },
  heat: { name: "Miami Heat", shortName: "Heat" },
  "milwaukee bucks": { name: "Milwaukee Bucks", shortName: "Bucks" },
  bucks: { name: "Milwaukee Bucks", shortName: "Bucks" },
  "minnesota timberw": { name: "Minnesota Timberwolves", shortName: "Timberwolves" },
  timberwolves: { name: "Minnesota Timberwolves", shortName: "Timberwolves" },
  "new orleans pelic": { name: "New Orleans Pelicans", shortName: "Pelicans" },
  pelicans: { name: "New Orleans Pelicans", shortName: "Pelicans" },
  "new york knicks": { name: "New York Knicks", shortName: "Knicks" },
  knicks: { name: "New York Knicks", shortName: "Knicks" },
  "oklahoma city thu": { name: "Oklahoma City Thunder", shortName: "Thunder" },
  thunder: { name: "Oklahoma City Thunder", shortName: "Thunder" },
  "orlando magic": { name: "Orlando Magic", shortName: "Magic" },
  magic: { name: "Orlando Magic", shortName: "Magic" },
  "philadelphia 76er": { name: "Philadelphia 76ers", shortName: "76ers" },
  "philadelphia 76ers": { name: "Philadelphia 76ers", shortName: "76ers" },
  sixers: { name: "Philadelphia 76ers", shortName: "76ers" },
  "phoenix suns": { name: "Phoenix Suns", shortName: "Suns" },
  suns: { name: "Phoenix Suns", shortName: "Suns" },
  "portland trail bl": { name: "Portland Trail Blazers", shortName: "Trail Blazers" },
  blazers: { name: "Portland Trail Blazers", shortName: "Trail Blazers" },
  "sacramento kings": { name: "Sacramento Kings", shortName: "Kings" },
  kings: { name: "Sacramento Kings", shortName: "Kings" },
  "san antonio spurs": { name: "San Antonio Spurs", shortName: "Spurs" },
  spurs: { name: "San Antonio Spurs", shortName: "Spurs" },
  "toronto raptors": { name: "Toronto Raptors", shortName: "Raptors" },
  raptors: { name: "Toronto Raptors", shortName: "Raptors" },
  "utah jazz": { name: "Utah Jazz", shortName: "Jazz" },
  jazz: { name: "Utah Jazz", shortName: "Jazz" },
  "washington wizard": { name: "Washington Wizards", shortName: "Wizards" },
  wizards: { name: "Washington Wizards", shortName: "Wizards" },
};

export const MLB_TEAM_META: Record<string, { name: string; shortName: string }> = {
  "arizona diamondba": { name: "Arizona Diamondbacks", shortName: "Diamondbacks" },
  athletics: { name: "Oakland Athletics", shortName: "Athletics" },
  "atlanta braves": { name: "Atlanta Braves", shortName: "Braves" },
  "baltimore orioles": { name: "Baltimore Orioles", shortName: "Orioles" },
  "boston red sox": { name: "Boston Red Sox", shortName: "Red Sox" },
  "chicago cubs": { name: "Chicago Cubs", shortName: "Cubs" },
  "chicago white sox": { name: "Chicago White Sox", shortName: "White Sox" },
  "cincinnati reds": { name: "Cincinnati Reds", shortName: "Reds" },
  "cleveland guardia": { name: "Cleveland Guardians", shortName: "Guardians" },
  "colorado rockies": { name: "Colorado Rockies", shortName: "Rockies" },
  "detroit tigers": { name: "Detroit Tigers", shortName: "Tigers" },
  "houston astros": { name: "Houston Astros", shortName: "Astros" },
  "kansas city royal": { name: "Kansas City Royals", shortName: "Royals" },
  "los angeles angel": { name: "Los Angeles Angels", shortName: "Angels" },
  "los angeles dodge": { name: "Los Angeles Dodgers", shortName: "Dodgers" },
  "miami marlins": { name: "Miami Marlins", shortName: "Marlins" },
  "milwaukee brewers": { name: "Milwaukee Brewers", shortName: "Brewers" },
  "minnesota twins": { name: "Minnesota Twins", shortName: "Twins" },
  "new york mets": { name: "New York Mets", shortName: "Mets" },
  "new york yankees": { name: "New York Yankees", shortName: "Yankees" },
  "philadelphia phil": { name: "Philadelphia Phillies", shortName: "Phillies" },
  "pittsburgh pirate": { name: "Pittsburgh Pirates", shortName: "Pirates" },
  "san diego padres": { name: "San Diego Padres", shortName: "Padres" },
  "san francisco gia": { name: "San Francisco Giants", shortName: "Giants" },
  "seattle mariners": { name: "Seattle Mariners", shortName: "Mariners" },
  "st. louis cardina": { name: "St. Louis Cardinals", shortName: "Cardinals" },
  "tampa bay rays": { name: "Tampa Bay Rays", shortName: "Rays" },
  "texas rangers": { name: "Texas Rangers", shortName: "Rangers" },
  "toronto blue jays": { name: "Toronto Blue Jays", shortName: "Blue Jays" },
  "washington nation": { name: "Washington Nationals", shortName: "Nationals" },
};

export const NHL_TEAM_META: Record<string, { name: string; shortName: string }> = {
  "anaheim ducks": { name: "Anaheim Ducks", shortName: "Ducks" },
  "boston bruins": { name: "Boston Bruins", shortName: "Bruins" },
  "buffalo sabres": { name: "Buffalo Sabres", shortName: "Sabres" },
  "calgary flames": { name: "Calgary Flames", shortName: "Flames" },
  "carolina hurrican": { name: "Carolina Hurricanes", shortName: "Hurricanes" },
  "chicago blackhawk": { name: "Chicago Blackhawks", shortName: "Blackhawks" },
  "colorado avalanch": { name: "Colorado Avalanche", shortName: "Avalanche" },
  "columbus blue jac": { name: "Columbus Blue Jackets", shortName: "Blue Jackets" },
  "dallas stars": { name: "Dallas Stars", shortName: "Stars" },
  "detroit red wings": { name: "Detroit Red Wings", shortName: "Red Wings" },
  "edmonton oilers": { name: "Edmonton Oilers", shortName: "Oilers" },
  "florida panthers": { name: "Florida Panthers", shortName: "Panthers" },
  "los angeles kings": { name: "Los Angeles Kings", shortName: "Kings" },
  "minnesota wild": { name: "Minnesota Wild", shortName: "Wild" },
  "montreal canadien": { name: "Montreal Canadiens", shortName: "Canadiens" },
  "nashville predato": { name: "Nashville Predators", shortName: "Predators" },
  "new jersey devils": { name: "New Jersey Devils", shortName: "Devils" },
  "new york islander": { name: "New York Islanders", shortName: "Islanders" },
  "new york rangers": { name: "New York Rangers", shortName: "Rangers" },
  "ottawa senators": { name: "Ottawa Senators", shortName: "Senators" },
  "philadelphia flye": { name: "Philadelphia Flyers", shortName: "Flyers" },
  "pittsburgh pengu": { name: "Pittsburgh Penguins", shortName: "Penguins" },
  "san jose sharks": { name: "San Jose Sharks", shortName: "Sharks" },
  "seattle kraken": { name: "Seattle Kraken", shortName: "Kraken" },
  "st. louis blues": { name: "St. Louis Blues", shortName: "Blues" },
  "tampa bay lightni": { name: "Tampa Bay Lightning", shortName: "Lightning" },
  "toronto maple lea": { name: "Toronto Maple Leafs", shortName: "Maple Leafs" },
  "utah mammoth": { name: "Utah Mammoth", shortName: "Mammoth" },
  "vancouver canucks": { name: "Vancouver Canucks", shortName: "Canucks" },
  "vegas golden knig": { name: "Vegas Golden Knights", shortName: "Golden Knights" },
  "washington capita": { name: "Washington Capitals", shortName: "Capitals" },
  "winnipeg jets": { name: "Winnipeg Jets", shortName: "Jets" },
};

export const NFL_TEAM_META: Record<string, { name: string; shortName: string }> = {
  "arizona cardinals": { name: "Arizona Cardinals", shortName: "Cardinals" },
  "atlanta falcons": { name: "Atlanta Falcons", shortName: "Falcons" },
  "baltimore ravens": { name: "Baltimore Ravens", shortName: "Ravens" },
  "buffalo bills": { name: "Buffalo Bills", shortName: "Bills" },
  "carolina panthers": { name: "Carolina Panthers", shortName: "Panthers" },
  "chicago bears": { name: "Chicago Bears", shortName: "Bears" },
  "cincinnati bengal": { name: "Cincinnati Bengals", shortName: "Bengals" },
  "cleveland browns": { name: "Cleveland Browns", shortName: "Browns" },
  "dallas cowboys": { name: "Dallas Cowboys", shortName: "Cowboys" },
  "denver broncos": { name: "Denver Broncos", shortName: "Broncos" },
  "detroit lions": { name: "Detroit Lions", shortName: "Lions" },
  "green bay packers": { name: "Green Bay Packers", shortName: "Packers" },
  "houston texans": { name: "Houston Texans", shortName: "Texans" },
  "indianapolis colt": { name: "Indianapolis Colts", shortName: "Colts" },
  "jacksonville jagu": { name: "Jacksonville Jaguars", shortName: "Jaguars" },
  "kansas city chief": { name: "Kansas City Chiefs", shortName: "Chiefs" },
  "las vegas raiders": { name: "Las Vegas Raiders", shortName: "Raiders" },
  "los angeles charg": { name: "Los Angeles Chargers", shortName: "Chargers" },
  "los angeles rams": { name: "Los Angeles Rams", shortName: "Rams" },
  "miami dolphins": { name: "Miami Dolphins", shortName: "Dolphins" },
  "minnesota vikings": { name: "Minnesota Vikings", shortName: "Vikings" },
  "new england patri": { name: "New England Patriots", shortName: "Patriots" },
  "new orleans saint": { name: "New Orleans Saints", shortName: "Saints" },
  "new york giants": { name: "New York Giants", shortName: "Giants" },
  "new york jets": { name: "New York Jets", shortName: "Jets" },
  "philadelphia eagl": { name: "Philadelphia Eagles", shortName: "Eagles" },
  "pittsburgh steele": { name: "Pittsburgh Steelers", shortName: "Steelers" },
  "san francisco 49e": { name: "San Francisco 49ers", shortName: "49ers" },
  "seattle seahawks": { name: "Seattle Seahawks", shortName: "Seahawks" },
  "tampa bay buccane": { name: "Tampa Bay Buccaneers", shortName: "Buccaneers" },
  "tennessee titans": { name: "Tennessee Titans", shortName: "Titans" },
  "washington comman": { name: "Washington Commanders", shortName: "Commanders" },
};

export const WNBA_TEAM_META: Record<string, { name: string; shortName: string }> = {
  "atlanta dream": { name: "Atlanta Dream", shortName: "Dream" },
  "chicago sky": { name: "Chicago Sky", shortName: "Sky" },
  "connecticut sun": { name: "Connecticut Sun", shortName: "Sun" },
  "dallas wings": { name: "Dallas Wings", shortName: "Wings" },
  "golden state va": { name: "Golden State Valkyries", shortName: "Valkyries" },
  "indiana fever": { name: "Indiana Fever", shortName: "Fever" },
  "las vegas aces": { name: "Las Vegas Aces", shortName: "Aces" },
  "los angeles spa": { name: "Los Angeles Sparks", shortName: "Sparks" },
  "minnesota lynx": { name: "Minnesota Lynx", shortName: "Lynx" },
  "new york libert": { name: "New York Liberty", shortName: "Liberty" },
  "phoenix mercury": { name: "Phoenix Mercury", shortName: "Mercury" },
  "portland fire": { name: "Portland Fire", shortName: "Fire" },
  "seattle storm": { name: "Seattle Storm", shortName: "Storm" },
  "toronto tempo": { name: "Toronto Tempo", shortName: "Tempo" },
  "washington myst": { name: "Washington Mystics", shortName: "Mystics" },
};

export const LEAGUE_TEAM_META: Record<string, { name: string; shortName: string }> = {
  ...NBA_TEAM_META,
  ...MLB_TEAM_META,
  ...NHL_TEAM_META,
  ...NFL_TEAM_META,
  ...WNBA_TEAM_META,
};
